In [31]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

In [32]:
from google.colab import files
uploaded = files.upload()

Saving student.csv to student (1).csv

In [33]:
df = pd.read_csv('student.csv')

In [34]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06

In [35]:
print("="*50)
print("🎯 ข้อมูลหลัก (Master Dataset) ที่จะใช้ตลอดบทเรียน")
print("="*50)
print(df_master)
print("\n📊 สรุปปัญหาที่พบในข้อมูล:")
print(f"- ค่าหายทั้งหมด: {df_master.isnull().sum().sum()} ค่า")
print(f"- อายุผิดปกติ: {df_master[df_master['อายุ'] > 100]['อายุ'].values if any(df_master['อายุ'] > 100) else 'ไม่มี'}")
print(f"- GPA ผิดปกติ: {df_master[(df_master['GPA'] < 0) | (df_master['GPA'] > 4)]['GPA'].values if any((df_master['GPA'] < 0) | (df_master['GPA'] > 4)) else 'ไม่มี'}")
print(f"- รูปแบบการเขียนคณะ: {df_master['คณะ'].nunique()} แบบ")
print(f"- รูปแบบการเขียนเพศ: {df_master['เพศ'].nunique()} แบบ")

==================================================
🎯 ข้อมูลหลัก (Master Dataset) ที่จะใช้ตลอดบทเรียน
==================================================
    รหัสนักศึกษา      ชื่อ   อายุ     เพศ             คณะ   GPA  ส่วนสูง_cm  \
0          64001     สมชาย   20.0     ชาย     วิทยาศาสตร์  3.21       170.0
1          64002    สมหญิง   21.0    หญิง           วิทย์  3.45       165.0
2          64003       NaN    NaN    Male         Science  3.67       175.0
3          64004  สมศักดิ์   22.0       ช  คณะวิทยาศาสตร์ -1.00       168.0
4          64005      สมใจ   19.0       ญ           วิศวะ  3.89       160.0
5          64006     กานต์  150.0     ชาย     Engineering  3.12       172.0
6          64007     กิตติ   21.0    หญิง        วิศวกรรม  4.50       158.0
7          64008      จิรา   20.0       F      ศิลปศาสตร์  2.98       180.0
8          64009    ชนาธิป   23.0       M            Arts  3.34       163.0
9          64010      ดารา   21.0    หญิง           ศิลป์  3.56       167.0
10         64011      ธีระ    NaN     NaN             NaN  3.78         NaN
11         64012       นภา   22.0     ชาย           วิทย์   NaN       171.0
12         64013     บุญมี   20.0    หญิง           วิศวฯ  3.23       169.0
13         64014     ปรีชา   21.0     ชาย    Liberal Arts  3.45       164.0
14         64015     พิมพ์   22.0  Female             Sci  3.67       162.0
15         64016      ภูมิ   19.0       ช     วิทยาศาสตร์  3.89       173.0
16         64017      มานี   20.0       ญ  วิศวกรรมศาสตร์  3.01       166.0
17         64018      ยุพา   21.0    หญิง             NaN  3.23       161.0
18         64019     รัตนา    NaN     ชาย      ศิลปศาสตร์   NaN       174.0
19         64020     ลัดดา   22.0     NaN         Science  3.45       168.0

    น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0         65.0                     15.0      2024-01-23
1         58.0                     20.0      2024-02-05
2          NaN                     25.0      2024-01-13
3         70.0                     10.0      2023-12-30
4         52.0                     30.0      2024-01-27
5         75.0                     12.0      2023-12-23
6         48.0                     35.0      2024-01-05
7         82.0                     18.0      2024-01-23
8         55.0                     22.0      2024-02-11
9         60.0                     28.0      2024-01-03
10        68.0                      NaN      2024-01-07
11         NaN                     16.0      2023-12-26
12        72.0                     24.0      2023-12-26
13        54.0                     19.0      2024-01-08
14        56.0                     26.0      2024-02-06
15        78.0                     14.0      2024-01-20
16        62.0                     21.0      2024-01-24
17        50.0                     27.0      2024-01-08
18        76.0                      NaN      2023-12-18
19        64.0                     23.0      2024-01-06

📊 สรุปปัญหาที่พบในข้อมูล:
- ค่าหายทั้งหมด: 15 ค่า
- อายุผิดปกติ: [150.]
- GPA ผิดปกติ: [-1.   4.5]
- รูปแบบการเขียนคณะ: 14 แบบ
- รูปแบบการเขียนเพศ: 8 แบบ

In [36]:
print("ก่อนเติมค่า")
df

ก่อนเติมค่า

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06

In [37]:
mean_age = df['อายุ'].mean()
df['อายุ'].fillna(mean_age, inplace=True)
mean_kg = df['น้ำหนัก_kg'].mean()
df['น้ำหนัก_kg'].fillna(mean_kg, inplace=True)
mean_cm = df['ส่วนสูง_cm'].mean()
df['ส่วนสูง_cm'].fillna(mean_cm, inplace=True)
mean_hr = df['ชั่วโมงเรียน_ต่อสัปดาห์'].mean()
df['ชั่วโมงเรียน_ต่อสัปดาห์'].fillna(mean_hr, inplace=True)
mean_gpa = df['GPA'].mean()
df['GPA'].fillna(mean_gpa, inplace=True)

In [38]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.000000,2024-01-23
1,64002,สมหญิง,21.000000,หญิง,วิทย์,3.450000,165.000000,58.000000,20.000000,2024-02-05
2,64003,NaN,28.470588,Male,Science,3.670000,175.000000,63.611111,25.000000,2024-01-13
3,64004,สมศักดิ์,22.000000,ช,คณะวิทยาศาสตร์,-1.000000,168.000000,70.000000,10.000000,2023-12-30
4,64005,สมใจ,19.000000,ญ,วิศวะ,3.890000,160.000000,52.000000,30.000000,2024-01-27
5,64006,กานต์,150.000000,ชาย,Engineering,3.120000,172.000000,75.000000,12.000000,2023-12-23
6,64007,กิตติ,21.000000,หญิง,วิศวกรรม,4.500000,158.000000,48.000000,35.000000,2024-01-05
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.000000,2024-01-23
8,64009,ชนาธิป,23.000000,M,Arts,3.340000,163.000000,55.000000,22.000000,2024-02-11
9,64010,ดารา,21.000000,หญิง,ศิลป์,3.560000,167.000000,60.000000,28.000000,2024-01-03
10,64011,ธีระ,28.470588,NaN,NaN,3.780000,167.684211,68.000000,21.388889,2024-01-07
11,64012,นภา,22.000000,ชาย,วิทย์,3.246111,171.000000,63.611111,16.000000,2023-12-26
12,64013,บุญมี,20.000000,หญิง,วิศวฯ,3.230000,169.000000,72.000000,24.000000,2023-12-26
13,64014,ปรีชา,21.000000,ชาย,Liberal Arts,3.450000,164.000000,54.000000,19.000000,2024-01-08
14,64015,พิมพ์,22.000000,Female,Sci,3.670000,162.000000,56.000000,26.000000,2024-02-06
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.000000,2024-01-20
16,64017,มานี,20.000000,ญ,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.000000,2024-01-24
17,64018,ยุพา,21.000000,หญิง,NaN,3.230000,161.000000,50.000000,27.000000,2024-01-08
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.000000,21.388889,2023-12-18
19,64020,ลัดดา,22.000000,NaN,Science,3.450000,168.000000,64.000000,23.000000,2024-01-06

In [42]:
df['คณะ'].fillna(df['คณะ'].mode()[0], inplace=True)
df['ชื่อ'].fillna(df['ชื่อ'].mode()[0], inplace=True)
df['เพศ'].fillna(df['เพศ'].mode()[0], inplace=True)

In [43]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.000000,2024-01-23
1,64002,สมหญิง,21.000000,หญิง,วิทย์,3.450000,165.000000,58.000000,20.000000,2024-02-05
2,64003,กานต์,28.470588,Male,Science,3.670000,175.000000,63.611111,25.000000,2024-01-13
3,64004,สมศักดิ์,22.000000,ช,คณะวิทยาศาสตร์,-1.000000,168.000000,70.000000,10.000000,2023-12-30
4,64005,สมใจ,19.000000,ญ,วิศวะ,3.890000,160.000000,52.000000,30.000000,2024-01-27
5,64006,กานต์,150.000000,ชาย,Engineering,3.120000,172.000000,75.000000,12.000000,2023-12-23
6,64007,กิตติ,21.000000,หญิง,วิศวกรรม,4.500000,158.000000,48.000000,35.000000,2024-01-05
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.000000,2024-01-23
8,64009,ชนาธิป,23.000000,M,Arts,3.340000,163.000000,55.000000,22.000000,2024-02-11
9,64010,ดารา,21.000000,หญิง,ศิลป์,3.560000,167.000000,60.000000,28.000000,2024-01-03
10,64011,ธีระ,28.470588,ชาย,Science,3.780000,167.684211,68.000000,21.388889,2024-01-07
11,64012,นภา,22.000000,ชาย,วิทย์,3.246111,171.000000,63.611111,16.000000,2023-12-26
12,64013,บุญมี,20.000000,หญิง,วิศวฯ,3.230000,169.000000,72.000000,24.000000,2023-12-26
13,64014,ปรีชา,21.000000,ชาย,Liberal Arts,3.450000,164.000000,54.000000,19.000000,2024-01-08
14,64015,พิมพ์,22.000000,Female,Sci,3.670000,162.000000,56.000000,26.000000,2024-02-06
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.000000,2024-01-20
16,64017,มานี,20.000000,ญ,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.000000,2024-01-24
17,64018,ยุพา,21.000000,หญิง,Science,3.230000,161.000000,50.000000,27.000000,2024-01-08
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.000000,21.388889,2023-12-18
19,64020,ลัดดา,22.000000,ชาย,Science,3.450000,168.000000,64.000000,23.000000,2024-01-06

In [53]:
def standardize_faculty(name):
    if name in ['วิทยาศาสตร์', 'วิทย์', 'Science', 'คณะวิทยาศาสตร์']:
        return 'วิทยาศาสตร์'
    elif name in ['ศิลปศาสตร์', 'ศิลป์', 'Arts','Liberal Arts']:
        return 'ศิลปศาสตร์'
    else:
        return 'วิศวกรรมศาสตร์'

In [54]:
df['คณะ'] = df['คณะ'].apply(standardize_faculty)

In [55]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,คณะ_มาตรฐาน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.000000,2024-01-23,วิทยาศาสตร์
1,64002,สมหญิง,21.000000,หญิง,วิทยาศาสตร์,3.450000,165.000000,58.000000,20.000000,2024-02-05,วิทยาศาสตร์
2,64003,กานต์,28.470588,Male,วิทยาศาสตร์,3.670000,175.000000,63.611111,25.000000,2024-01-13,วิทยาศาสตร์
3,64004,สมศักดิ์,22.000000,ช,วิทยาศาสตร์,-1.000000,168.000000,70.000000,10.000000,2023-12-30,วิทยาศาสตร์
4,64005,สมใจ,19.000000,ญ,วิศวกรรมศาสตร์,3.890000,160.000000,52.000000,30.000000,2024-01-27,วิศวะ
5,64006,กานต์,150.000000,ชาย,วิศวกรรมศาสตร์,3.120000,172.000000,75.000000,12.000000,2023-12-23,Engineering
6,64007,กิตติ,21.000000,หญิง,วิศวกรรมศาสตร์,4.500000,158.000000,48.000000,35.000000,2024-01-05,วิศวกรรม
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.000000,2024-01-23,ศิลปศาสตร์
8,64009,ชนาธิป,23.000000,M,ศิลปศาสตร์,3.340000,163.000000,55.000000,22.000000,2024-02-11,ศิลปศาสตร์
9,64010,ดารา,21.000000,หญิง,ศิลปศาสตร์,3.560000,167.000000,60.000000,28.000000,2024-01-03,ศิลปศาสตร์
10,64011,ธีระ,28.470588,ชาย,วิทยาศาสตร์,3.780000,167.684211,68.000000,21.388889,2024-01-07,วิทยาศาสตร์
11,64012,นภา,22.000000,ชาย,วิทยาศาสตร์,3.246111,171.000000,63.611111,16.000000,2023-12-26,วิทยาศาสตร์
12,64013,บุญมี,20.000000,หญิง,วิศวกรรมศาสตร์,3.230000,169.000000,72.000000,24.000000,2023-12-26,วิศวฯ
13,64014,ปรีชา,21.000000,ชาย,ศิลปศาสตร์,3.450000,164.000000,54.000000,19.000000,2024-01-08,Liberal Arts
14,64015,พิมพ์,22.000000,Female,วิศวกรรมศาสตร์,3.670000,162.000000,56.000000,26.000000,2024-02-06,Sci
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.000000,2024-01-20,วิทยาศาสตร์
16,64017,มานี,20.000000,ญ,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.000000,2024-01-24,วิศวกรรมศาสตร์
17,64018,ยุพา,21.000000,หญิง,วิทยาศาสตร์,3.230000,161.000000,50.000000,27.000000,2024-01-08,วิทยาศาสตร์
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.000000,21.388889,2023-12-18,ศิลปศาสตร์
19,64020,ลัดดา,22.000000,ชาย,วิทยาศาสตร์,3.450000,168.000000,64.000000,23.000000,2024-01-06,วิทยาศาสตร์

In [56]:
print("ข้อมูลต้นฉบับ")
print(df)
print(f"\nค่าเฉลี่ยอายุ (รวมค่าผิดปกติ) - {df['อายุ'].mean():.2f}")

ข้อมูลต้นฉบับ
    รหัสนักศึกษา      ชื่อ        อายุ     เพศ             คณะ       GPA  \
0          64001     สมชาย   20.000000     ชาย     วิทยาศาสตร์  3.210000
1          64002    สมหญิง   21.000000    หญิง     วิทยาศาสตร์  3.450000
2          64003     กานต์   28.470588    Male     วิทยาศาสตร์  3.670000
3          64004  สมศักดิ์   22.000000       ช     วิทยาศาสตร์ -1.000000
4          64005      สมใจ   19.000000       ญ  วิศวกรรมศาสตร์  3.890000
5          64006     กานต์  150.000000     ชาย  วิศวกรรมศาสตร์  3.120000
6          64007     กิตติ   21.000000    หญิง  วิศวกรรมศาสตร์  4.500000
7          64008      จิรา   20.000000       F      ศิลปศาสตร์  2.980000
8          64009    ชนาธิป   23.000000       M      ศิลปศาสตร์  3.340000
9          64010      ดารา   21.000000    หญิง      ศิลปศาสตร์  3.560000
10         64011      ธีระ   28.470588     ชาย     วิทยาศาสตร์  3.780000
11         64012       นภา   22.000000     ชาย     วิทยาศาสตร์  3.246111
12         64013     บุญมี   20.000000    หญิง  วิศวกรรมศาสตร์  3.230000
13         64014     ปรีชา   21.000000     ชาย      ศิลปศาสตร์  3.450000
14         64015     พิมพ์   22.000000  Female  วิศวกรรมศาสตร์  3.670000
15         64016      ภูมิ   19.000000       ช     วิทยาศาสตร์  3.890000
16         64017      มานี   20.000000       ญ  วิศวกรรมศาสตร์  3.010000
17         64018      ยุพา   21.000000    หญิง     วิทยาศาสตร์  3.230000
18         64019     รัตนา   28.470588     ชาย      ศิลปศาสตร์  3.246111
19         64020     ลัดดา   22.000000     ชาย     วิทยาศาสตร์  3.450000

    ส่วนสูง_cm  น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน  \
0   170.000000   65.000000                15.000000      2024-01-23
1   165.000000   58.000000                20.000000      2024-02-05
2   175.000000   63.611111                25.000000      2024-01-13
3   168.000000   70.000000                10.000000      2023-12-30
4   160.000000   52.000000                30.000000      2024-01-27
5   172.000000   75.000000                12.000000      2023-12-23
6   158.000000   48.000000                35.000000      2024-01-05
7   180.000000   82.000000                18.000000      2024-01-23
8   163.000000   55.000000                22.000000      2024-02-11
9   167.000000   60.000000                28.000000      2024-01-03
10  167.684211   68.000000                21.388889      2024-01-07
11  171.000000   63.611111                16.000000      2023-12-26
12  169.000000   72.000000                24.000000      2023-12-26
13  164.000000   54.000000                19.000000      2024-01-08
14  162.000000   56.000000                26.000000      2024-02-06
15  173.000000   78.000000                14.000000      2024-01-20
16  166.000000   62.000000                21.000000      2024-01-24
17  161.000000   50.000000                27.000000      2024-01-08
18  174.000000   76.000000                21.388889      2023-12-18
19  168.000000   64.000000                23.000000      2024-01-06

       คณะ_มาตรฐาน
0      วิทยาศาสตร์
1      วิทยาศาสตร์
2      วิทยาศาสตร์
3      วิทยาศาสตร์
4            วิศวะ
5      Engineering
6         วิศวกรรม
7       ศิลปศาสตร์
8       ศิลปศาสตร์
9       ศิลปศาสตร์
10     วิทยาศาสตร์
11     วิทยาศาสตร์
12           วิศวฯ
13    Liberal Arts
14             Sci
15     วิทยาศาสตร์
16  วิศวกรรมศาสตร์
17     วิทยาศาสตร์
18      ศิลปศาสตร์
19     วิทยาศาสตร์

ค่าเฉลี่ยอายุ (รวมค่าผิดปกติ) - 28.47

In [57]:
Q1 = df['อายุ'].quantile(0.25)
Q3 = df['อายุ'].quantile(0.75)
IQR = Q3 - Q1

In [58]:
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [59]:
df_no_outliers = df[(df['อายุ'] >= lower_bound) & (df['อายุ'] <= upper_bound)]

In [60]:
print(f"\nขอบเขตล่าง - {lower_bound}")
print(f"ขอบเขตบน - {upper_bound}")
print(f"\nข้อมูลหลังกรองค่าผิดปกติ")
print(df_no_outliers)
print(f"\nค่าเฉลี่ยอายุ (หลังกรองค่าผิดปกติ) - {df_no_outliers['อายุ'].mean():.2f}")

ขอบเขตล่าง - 16.625
ขอบเขตบน - 25.625

ข้อมูลหลังกรองค่าผิดปกติ
    รหัสนักศึกษา      ชื่อ  อายุ     เพศ             คณะ       GPA  \
0          64001     สมชาย  20.0     ชาย     วิทยาศาสตร์  3.210000
1          64002    สมหญิง  21.0    หญิง     วิทยาศาสตร์  3.450000
3          64004  สมศักดิ์  22.0       ช     วิทยาศาสตร์ -1.000000
4          64005      สมใจ  19.0       ญ  วิศวกรรมศาสตร์  3.890000
6          64007     กิตติ  21.0    หญิง  วิศวกรรมศาสตร์  4.500000
7          64008      จิรา  20.0       F      ศิลปศาสตร์  2.980000
8          64009    ชนาธิป  23.0       M      ศิลปศาสตร์  3.340000
9          64010      ดารา  21.0    หญิง      ศิลปศาสตร์  3.560000
11         64012       นภา  22.0     ชาย     วิทยาศาสตร์  3.246111
12         64013     บุญมี  20.0    หญิง  วิศวกรรมศาสตร์  3.230000
13         64014     ปรีชา  21.0     ชาย      ศิลปศาสตร์  3.450000
14         64015     พิมพ์  22.0  Female  วิศวกรรมศาสตร์  3.670000
15         64016      ภูมิ  19.0       ช     วิทยาศาสตร์  3.890000
16         64017      มานี  20.0       ญ  วิศวกรรมศาสตร์  3.010000
17         64018      ยุพา  21.0    หญิง     วิทยาศาสตร์  3.230000
19         64020     ลัดดา  22.0     ชาย     วิทยาศาสตร์  3.450000

    ส่วนสูง_cm  น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน  \
0        170.0   65.000000                     15.0      2024-01-23
1        165.0   58.000000                     20.0      2024-02-05
3        168.0   70.000000                     10.0      2023-12-30
4        160.0   52.000000                     30.0      2024-01-27
6        158.0   48.000000                     35.0      2024-01-05
7        180.0   82.000000                     18.0      2024-01-23
8        163.0   55.000000                     22.0      2024-02-11
9        167.0   60.000000                     28.0      2024-01-03
11       171.0   63.611111                     16.0      2023-12-26
12       169.0   72.000000                     24.0      2023-12-26
13       164.0   54.000000                     19.0      2024-01-08
14       162.0   56.000000                     26.0      2024-02-06
15       173.0   78.000000                     14.0      2024-01-20
16       166.0   62.000000                     21.0      2024-01-24
17       161.0   50.000000                     27.0      2024-01-08
19       168.0   64.000000                     23.0      2024-01-06

       คณะ_มาตรฐาน
0      วิทยาศาสตร์
1      วิทยาศาสตร์
3      วิทยาศาสตร์
4            วิศวะ
6         วิศวกรรม
7       ศิลปศาสตร์
8       ศิลปศาสตร์
9       ศิลปศาสตร์
11     วิทยาศาสตร์
12           วิศวฯ
13    Liberal Arts
14             Sci
15     วิทยาศาสตร์
16  วิศวกรรมศาสตร์
17     วิทยาศาสตร์
19     วิทยาศาสตร์

ค่าเฉลี่ยอายุ (หลังกรองค่าผิดปกติ) - 20.88

In [63]:
data_encoded = pd.get_dummies(df, columns=['คณะ'])
print(data_encoded)

    รหัสนักศึกษา      ชื่อ        อายุ     เพศ       GPA  ส่วนสูง_cm  \
0          64001     สมชาย   20.000000     ชาย  3.210000  170.000000
1          64002    สมหญิง   21.000000    หญิง  3.450000  165.000000
2          64003     กานต์   28.470588    Male  3.670000  175.000000
3          64004  สมศักดิ์   22.000000       ช -1.000000  168.000000
4          64005      สมใจ   19.000000       ญ  3.890000  160.000000
5          64006     กานต์  150.000000     ชาย  3.120000  172.000000
6          64007     กิตติ   21.000000    หญิง  4.500000  158.000000
7          64008      จิรา   20.000000       F  2.980000  180.000000
8          64009    ชนาธิป   23.000000       M  3.340000  163.000000
9          64010      ดารา   21.000000    หญิง  3.560000  167.000000
10         64011      ธีระ   28.470588     ชาย  3.780000  167.684211
11         64012       นภา   22.000000     ชาย  3.246111  171.000000
12         64013     บุญมี   20.000000    หญิง  3.230000  169.000000
13         64014     ปรีชา   21.000000     ชาย  3.450000  164.000000
14         64015     พิมพ์   22.000000  Female  3.670000  162.000000
15         64016      ภูมิ   19.000000       ช  3.890000  173.000000
16         64017      มานี   20.000000       ญ  3.010000  166.000000
17         64018      ยุพา   21.000000    หญิง  3.230000  161.000000
18         64019     รัตนา   28.470588     ชาย  3.246111  174.000000
19         64020     ลัดดา   22.000000     ชาย  3.450000  168.000000

    น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน     คณะ_มาตรฐาน  \
0    65.000000                15.000000      2024-01-23     วิทยาศาสตร์
1    58.000000                20.000000      2024-02-05     วิทยาศาสตร์
2    63.611111                25.000000      2024-01-13     วิทยาศาสตร์
3    70.000000                10.000000      2023-12-30     วิทยาศาสตร์
4    52.000000                30.000000      2024-01-27           วิศวะ
5    75.000000                12.000000      2023-12-23     Engineering
6    48.000000                35.000000      2024-01-05        วิศวกรรม
7    82.000000                18.000000      2024-01-23      ศิลปศาสตร์
8    55.000000                22.000000      2024-02-11      ศิลปศาสตร์
9    60.000000                28.000000      2024-01-03      ศิลปศาสตร์
10   68.000000                21.388889      2024-01-07     วิทยาศาสตร์
11   63.611111                16.000000      2023-12-26     วิทยาศาสตร์
12   72.000000                24.000000      2023-12-26           วิศวฯ
13   54.000000                19.000000      2024-01-08    Liberal Arts
14   56.000000                26.000000      2024-02-06             Sci
15   78.000000                14.000000      2024-01-20     วิทยาศาสตร์
16   62.000000                21.000000      2024-01-24  วิศวกรรมศาสตร์
17   50.000000                27.000000      2024-01-08     วิทยาศาสตร์
18   76.000000                21.388889      2023-12-18      ศิลปศาสตร์
19   64.000000                23.000000      2024-01-06     วิทยาศาสตร์

    คณะ_วิทยาศาสตร์  คณะ_วิศวกรรมศาสตร์  คณะ_ศิลปศาสตร์
0              True               False           False
1              True               False           False
2              True               False           False
3              True               False           False
4             False                True           False
5             False                True           False
6             False                True           False
7             False               False            True
8             False               False            True
9             False               False            True
10             True               False           False
11             True               False           False
12            False                True           False
13            False               False            True
14            False                True           False
15             True               False           False
16            False                True           False
17             True               False           False
18            False               False            True
19             True               False           False

In [64]:
df['BMI'] = df['น้ำหนัก_kg'] / (df['ส่วนสูง_cm']/100)**2
df['สุขภาพ'] = pd.cut(df['BMI'],
                                   bins=[0, 18.5, 25, 30, 100],
                                   labels=['ผอม', 'ปกติ', 'อ้วน', 'อ้วนมาก'])

print(df[['ชื่อ', 'BMI', 'สุขภาพ']])

        ชื่อ        BMI สุขภาพ
0      สมชาย  22.491349   ปกติ
1     สมหญิง  21.303949   ปกติ
2      กานต์  20.770975   ปกติ
3   สมศักดิ์  24.801587   ปกติ
4       สมใจ  20.312500   ปกติ
5      กานต์  25.351541   อ้วน
6      กิตติ  19.227688   ปกติ
7       จิรา  25.308642   อ้วน
8     ชนาธิป  20.700817   ปกติ
9       ดารา  21.513859   ปกติ
10      ธีระ  24.183802   ปกติ
11       นภา  21.754082   ปกติ
12     บุญมี  25.209201   อ้วน
13     ปรีชา  20.077335   ปกติ
14     พิมพ์  21.338211   ปกติ
15      ภูมิ  26.061679   อ้วน
16      มานี  22.499637   ปกติ
17      ยุพา  19.289379   ปกติ
18     รัตนา  25.102391   อ้วน
19     ลัดดา  22.675737   ปกติ